name: Build

on: [push, pull_request]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn coverage
